### ISSUE TITLE
Suggestion: add GitHub Actions example

### ISSUE THREAD

**Issue by trevordmiller** [rust-lang-nursery/cli-wg#161]
It would be helpful to have a GitHub Actions example to go along with the Travis CI / Trust items in https://rust-lang-nursery.github.io/cli-wg/tutorial/packaging.html.

**Comment by trevordmiller** [comment]
I'd be willing to submit a pull request for this, but as a new Rust developer, I've been trying to find this information myself. I could just use Travis CI, but I was hoping to keep all my development in GitHub if possible.

**Comment by trevordmiller** [comment]
It seems to me that CI could do something like:

```sh
cargo check
cargo test
cargo clippy
cargo fmt
```

And CD something like:

```sh
cargo doc
cargo build --release
# how to share executables to GitHub releases / packages?
```

**Comment by deg4uss3r** [comment]
I think this is more for a "Rust CI book" rather than the CLI WG. Since if we did an example for GitHub Actions we would probably need to have one for Jenkins, Travis, Appveyor, and so on. 

I do like the idea of a Rust CI book though, that would be really helpful!

**Comment by epage** [comment]
My recommendation has been that solving these types of problems are best handled in a dedicated resource, like [crate-ci](https://github.com/crate-ci/crate-ci.github.io/).  I've not had much time for updating it lately.  Though the crate-ci book doesn't reference Azure Pipelines, we have a separate page for azure pipelines and azure pipeline templates.  I do need to link out to uploading tarballs to Github Releases.

i see it natural to also consolidate Github Action templates and documentation over there as well.

**Comment by trevordmiller** [comment]
Here is what I ended up with, in case it is helpful:

## Run CI when pushing to branches for pull requeests

```yaml
name: Pull request
on:
  push:
    branches-ignore:
      - master
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Check
      run: cargo check
    - name: Test
      run: cargo test
    - name: Lint
      run: cargo clippy --all-targets -- -D warnings
    - name: Format
      run: cargo fmt -- --check
    - name: Publish
      run: cargo publish --dry-run
```

## Run CI and CD when merging pull requests to master

```yaml
name: Merge
on:
  push:
    branches:
      - master
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Check
      run: cargo check
    - name: Test
      run: cargo test
    - name: Lint
      run: cargo clippy --all-targets -- -D warnings
    - name: Format
      run: cargo fmt -- --check
  executable:
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Login
      run: cargo login ${{ secrets.CRATE_REGISTRY_PAT }}
    - name: Publish
      if: success()
      run: cargo publish
```
